### ISSUE TITLE
Not defined publicPath !!!

### ISSUE THREAD

**Issue by Kimel1** [elios264/react-starter#2]
Thank you for good boilerplate!!

I suggest  to add `publicPath: '/' ` in webpack config, because without it, webpack try to find app.bundle.js relative to current path. So if I go to http://localhost/products/create , I got error: can't get http://localhost/products/create/app.bundle.js

`output: { path: path.resolve(__dirname, './dist'), filename: isDev ? 'app.bundle.js' : 'app.bundle.[chunkhash].js', publicPath: '/' },`

**Comment by elios264** [comment]
Hi @Kimel1 
Thanks! I certanly missed that one, thanks!, also please feel free to comment on any other issue or recomendation you find.
