### ISSUE TITLE
Combine reducers 

### ISSUE THREAD

**Issue by Kimel1** [elios264/react-starter#3]
I'm use this beautiful  with another approach to reducers, it can be useful for others. 

In appLoader.js add 
```
import * as reducers from 'reducers';
const reducer = combineReducers({ ...reducers });  // in your starter-kit you use MainReducer name 
```
In reducers/index.js   
```
export { default as courseUsd } from './courseUsd';    
export default {};
```
reducers/courceUsd.js 

```
import { FETCH_COURSEUSD_FULFILLED, FETCH_COURSEUSDLAST_FULFILLED } from 'constants/action-types';

const initialState = {
  values: [],
  value: null
}
export default function courseUsd(state = initialState, action = {}) {
  switch (action.type) {
    case FETCH_COURSEUSD_FULFILLED:
      return {...state, values: action.values}
    case FETCH_COURSEUSDLAST_FULFILLED:
      return {...state, value: action.value}

    default:
      return state;
  }
}

```

It is just example, but it makes obvious how to combine reducers, you can simplify this code and add. As for me that is easy to combine new reducers. 

And another thing, you have a component folder and  you have app.js inside  which is a container because it connected to a redux.

**Comment by elios264** [comment]
Hi @Kimel1  

Addressing your fist suggestion, Its a good idea where you just add the reducers and they are automatically combined, but this suggestion only works when you use a simple reducer thechnique,  I suggest you have a read to: [http://redux.js.org/docs/recipes/reducers/BeyondCombineReducers.html](url)

I've myself been in the need to drop this approach and use a more sophisticated way to create my main reducer.  

And about your second suggestion about categorizing my react components in two folders: components & containers, I tried doing that when I was starting with React but in practice is much more comfortable to use the app-logic instead: 

![2222](https://user-images.githubusercontent.com/15863852/28582418-ed214798-712a-11e7-9cd8-d716af94d117.PNG)
![111](https://user-images.githubusercontent.com/15863852/28582419-ed3a0ed6-712a-11e7-9764-eec0a3c09eba.PNG)
